### ISSUE TITLE
Update documentation for the `Content Groups` API family

### ISSUE THREAD

**Issue by CarlosDamasio** [MicroStrategy/rest-api-docs#12]
The schema documentation for the patch `/api/contentGroups/{id}/contents` is not correct, and at the moment I can't figure what body and/or parameters should be defined to correctly request a content group patch via the REST api.

Therefore I'm requesting to update the documentation so it correctly reflects what the API is expecting for that specific endpoint, I believe it is a functional endpoint as is most likely being used by workstation.

**Comment by xdumstr** [comment]
@CarlosDamasio Thank you for reporting this to us. We have created a set of new documents for [contentGroups](https://microstrategy.github.io/rest-api-docs/common-workflows/manage-content-group-objects/).  Please take a look.  The schema error in https://demo.microstrategy.com/MicroStrategyLibrary/api-docs will be fixed in our Q4 release.

**Comment by CarlosDamasio** [comment]
@xdumstr Just tested things at my end using the new documentation and it's all working now. 
Thank you for the quick response and looking forward to see the updated api-docs in your Q4 release.
